# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

scheduling:
  enabled: true

fixedRate:
  in:
    milliseconds: 300000 # 5 minutes

spring:
  application:
    name: db-converter
  datasource:
    name: source
    jdbc-url: jdbc:postgresql://localhost:5432/opensrp
    username: opensrp_admin
    password: admin
    driver-class-name: org.postgresql.Driver
  target-datasource:
    name: target
    jdbc-url: jdbc:postgresql://localhost:5432/dbconverter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

source-database:
  tables:
  - targetTableName: ${target-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      AND "json" ->> 'firstName' != '-'
      AND "json" ->> 'lastName' != '-'
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0
  - targetTableName: ${target-database.tables[1].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[1].name}
      WHERE ${source-database.tables[1].idColumnName} > %s
      ORDER BY ${source-database.tables[1].idColumnName} ASC
    idColumnName: id
    lastId: 0

target-database:
  tables:
  - name: sid3.client_ibu
    columns:
    - name: document_id
      type: varchar(75)
      sourceColumnType: json
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      type: timestamp
      sourceColumnType: json
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      type: varchar(75)
      sourceColumnType: json
      sourceColumnName: json
      jsonPath: $.baseEntityId
  - name: sid3.identitas_ibu
    columns:
    - name: document_id
      type: varchar(75)
      sourceColumnType: json
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      type: timestamp
      sourceColumnType: json
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      type: varchar(75)
      sourceColumnType: json
      sourceColumnName: json
      jsonPath: $.baseEntityId