# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

scheduling:
  enabled: true

fixedRate:
  in:
    milliseconds: 300000 # 5 minutes

spring:
  application:
    name: db-converter
  config:
    import:
    - source-database.yml
    - destination-database.yml  
  datasource:
    name: source
    jdbc-url: jdbc:postgresql://localhost:5432/opensrp
    username: opensrp_admin
    password: admin
    driver-class-name: org.postgresql.Driver
  destination-datasource:
    name: destination
    jdbc-url: jdbc:postgresql://localhost:5432/dbconverter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
