# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

scheduling:
  enabled: true

fixedRate:
  in:
    milliseconds: 300000 # 5 minutes

spring:
  application:
    name: db-converter
  datasource:
    name: source
    jdbc-url: jdbc:postgresql://localhost:5432/opensrp
    username: opensrp_admin
    password: admin
    driver-class-name: org.postgresql.Driver
  target-datasource:
    name: target
    jdbc-url: jdbc:postgresql://localhost:5432/dbconverter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

source-database:
  tables:
  - targetTableName: ${target-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      AND "json" ->> 'firstName' != '-'
      AND "json" ->> 'lastName' != '-'
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0
  - targetTableName: ${target-database.tables[1].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[1].name}
      WHERE ${source-database.tables[1].idColumnName} > %s
      ORDER BY ${source-database.tables[1].idColumnName} ASC
    idColumnName: id
    lastId: 0

target-database:
  schemaName: sid3
  tables:
  - name: ${target-database.schemaName}.client_ibu
    columns:
    - name: source_${target-database.tables[0].columns[0].sourceColumnName}
      type: ${target-database.tables[0].columns[0].sourceColumnType}
      sourceColumnName: id
      sourceColumnType: bigserial
    - name: source_${target-database.tables[0].columns[1].sourceColumnName}
      type: ${target-database.tables[0].columns[1].sourceColumnType}
      sourceColumnName: date_deleted
      sourceColumnType: timestamp
    - name: source_${target-database.tables[0].columns[2].sourceColumnName}
      type: ${target-database.tables[0].columns[2].sourceColumnType}
      sourceColumnName: server_version
      sourceColumnType: int8
    - name: document_id
      type: varchar(75)
      sourceColumnName: json
      sourceColumnType: json
      jsonPath: $._id
    - name: date_created
      type: timestamp
      sourceColumnName: json
      sourceColumnType: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      type: varchar(75)
      sourceColumnName: json
      sourceColumnType: json
      jsonPath: $.baseEntityId
    query: INSERT INTO ${target-database.tables[0].name} (
      ${target-database.tables[0].columns[0].name}, ${target-database.tables[0].columns[1].name}, 
      ${target-database.tables[0].columns[2].name}, ${target-database.tables[0].columns[3].name}, 
      ${target-database.tables[0].columns[4].name}, ${target-database.tables[0].columns[5].name}
      ) VALUES (
        :${target-database.tables[0].columns[0].name}, :${target-database.tables[0].columns[1].name},
        :${target-database.tables[0].columns[2].name}, :${target-database.tables[0].columns[3].name},
        :${target-database.tables[0].columns[4].name}, :${target-database.tables[0].columns[5].name}
        )

  - name: ${target-database.schemaName}.identitas_ibu
    columns:
    - name: document_id
      type: varchar(75)
      sourceColumnName: json
      sourceColumnType: json
      jsonPath: $._id
    - name: date_created
      type: timestamp
      sourceColumnName: json
      sourceColumnType: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      type: varchar(75)
      sourceColumnName: json
      sourceColumnType: json
      jsonPath: $.baseEntityId