destination-database:
  schemaName: sid_anc
  tables:

  - name: ${destination-database.schemaName}.client
    columns:
    - name: source_id
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_date_deleted
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_server_version
      typeName: integer
      sourceColumnName: server_version
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: rev
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._rev
    - name: type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.type
    - name: gender
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.gender
    - name: first_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: last_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.lastName
    - name: home_address
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].addressFields.address2
    - name: age
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.age
    - name: estimated_delivery_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.edd
    - name: red_flag_count
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.red_flag_count
    - name: yellow_flag_count
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.yellow_flag_count
    - name: contact_status
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.contact_status
    - name: previous_contact_status
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.previous_contact_status
    - name: next_contact
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.next_contact
    - name: next_contact_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.next_contact_date
    - name: last_contact_record_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.last_contact_record_date
    - name: visit_start_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.visit_start_date
    - name: date_removed
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.date_removed
    - name: birth_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.birthdate
    - name: birthdate_approx
      typeName: boolean
      sourceColumnName: json
      jsonPath: $.birthdateApprox
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: date_edited
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateEdited
    - name: anc_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.identifiers.ANC_ID
    - name: server_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: client_database_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.clientDatabaseVersion
    - name: client_application_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.clientApplicationVersion

  - name: ${destination-database.schemaName}.anc_registration
    columns:
    - name: event_id
      typeName: varchar
      sourceColumnName: id
      isUnique: true
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: source_date_deleted
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_server_version
      typeName: integer
      sourceColumnName: server_version
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: rev
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._rev
    - name: team
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.team
    - name: type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.type
    - name: team_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.teamId
    - name: client_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.version
    - name: server_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: client_database_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.clientDatabaseVersion
    - name: client_application_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.clientApplicationVersion
    - name: duration
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.duration
    - name: event_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.eventDate
    - name: entity_type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.entityType
    - name: location_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.locationId
    - name: provider_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.providerId
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: form_submission_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.formSubmissionId
    - name: object_identifiers
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.identifiers
    - name: wom_image
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'wom_image')].values[0]
      jsonPath: $[0]
    - name: dob_calculated
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'dob_calculated')].values[0]
      jsonPath: $[0]
    - name: dob_entered
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'dob_entered')].values[0]
      jsonPath: $[0]
    - name: age_calculated
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'age_calculated')].values[0]
      jsonPath: $[0]
    - name: phone_number
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_number')].values[0]
      jsonPath: $[0]
    - name: reminders
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'reminders')].humanReadableValues[0]
      jsonPath: $[0]
    - name: alt_name
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'alt_name')].values[0]
      jsonPath: $[0]
    - name: alt_phone_number
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'alt_phone_number')].values[0]
      jsonPath: $[0]
    - name: cohabitants
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'cohabitants')].values[0]
      jsonPath: $
    - name: last_interacted_with
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'last_interacted_with')].values[0]
      jsonPath: $[0]
    - name: start_date_time
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'start')].values[0]
      jsonPath: $[0]
    - name: end_date_time
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'end')].values[0]
      jsonPath: $[0]
