destination-database:
  schemaName: sid3
  tables:
  - name: ${destination-database.schemaName}.client_ibu
    columns:
    - name: source_${destination-database.tables[0].columns[0].sourceColumnName}
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_${destination-database.tables[0].columns[1].sourceColumnName}
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_${destination-database.tables[0].columns[2].sourceColumnName}
      typeName: int8
      sourceColumnName: server_version
    - name: document_id
      typeName: varchar
      typeLength: 75
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      typeName: varchar
      typeLength: 75
      sourceColumnName: json
      jsonPath: $.baseEntityId
    query: INSERT INTO ${destination-database.tables[0].name} (
      ${destination-database.tables[0].columns[0].name}, ${destination-database.tables[0].columns[1].name}, 
      ${destination-database.tables[0].columns[2].name}, ${destination-database.tables[0].columns[3].name}, 
      ${destination-database.tables[0].columns[4].name}, ${destination-database.tables[0].columns[5].name}
      ) VALUES (
        :${destination-database.tables[0].columns[0].name}, :${destination-database.tables[0].columns[1].name},
        :${destination-database.tables[0].columns[2].name}, :${destination-database.tables[0].columns[3].name},
        :${destination-database.tables[0].columns[4].name}, :${destination-database.tables[0].columns[5].name}
        )
# TODO refactor the query, make it dynamic
  - name: ${destination-database.schemaName}.identitas_ibu
    columns:
    - name: document_id
      typeName: varchar
      typeLength: 75
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      typeName: varchar
      typeLength: 75
      sourceColumnName: json
      jsonPath: $.baseEntityId
