destination-database:
  schemaName: sid3
  tables:
  - name: ${destination-database.schemaName}.client_ibu
    columns:
    - name: source_${destination-database.tables[0].columns[0].sourceColumnName}
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_${destination-database.tables[0].columns[1].sourceColumnName}
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: full_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: husband_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.lastName
    - name: province
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].stateProvince
    - name: district
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].countyDistrict
    - name: village
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].cityVillage
    - name: address
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].addressFields.address3
    - name: gps
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].addressFields.gps
    - name: birth_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.birthdate
    - name: nik
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.nik
    - name: mother_registration_number
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.NoIbu
    - name: anc_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.anc_id
    - name: traditional_birth_attendant
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.NamaDukun
    - name: community_health_worker_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.NamaKader
    - name: server_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
  - name: ${destination-database.schemaName}.client_anak
    columns:
    - name: source_${destination-database.tables[1].columns[0].sourceColumnName}
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_${destination-database.tables[1].columns[1].sourceColumnName}
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: full_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: birth_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.birthdate
    - name: server_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: mother_base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.relationships.ibuCaseId[0]
    - name: openmrs_uuid
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.relationships.ibuCaseId[0]
    - name: gender
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.gender
    - name: date_edited
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateEdited
  - name: ${destination-database.schemaName}.identitas_ibu
    columns:
    - name: event_id
      typeName: varchar
      sourceColumnName: id
      isUnique: true
    - name: source_${destination-database.tables[2].columns[1].sourceColumnName}
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: mother_base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: location_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.locationId
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: event_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.eventDate
    - name: client_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.version
    - name: server_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: provider_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.providerId
    - name: registration_date
      typeName: date
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'registrationDate')].values[0]
      jsonPath: $[0]
    - name: mobile_phone_number
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'NomorTelponHp')].values[0]
      jsonPath: $[0]
    - name: checkup_location
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'lokasiPeriksa')].humanReadableValues[0]
      jsonPath: $[0]
    - name: other_checkup_location
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'lokasiPeriksaOther')].values[0]
      jsonPath: $[0]
    - name: patient_territory
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'pasienWilayah')].humanReadableValues[0]
      jsonPath: $[0]
    - name: education
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'pendidikan')].humanReadableValues[0]
      jsonPath: $[0]
    - name: integrated_healthcare_center
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'posyandu')].values[0]
      jsonPath: $[0]
    - name: blood_type
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'golonganDarah')].humanReadableValues[0]
      jsonPath: $[0]
    - name: life_insurance
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'asuransiJiwa')].humanReadableValues[0]
      jsonPath: $[0]
    - name: contraception_type
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'jenisKontrasepsi')].values[0]
      jsonPath: $[0]
    - name: is_transferred_patient
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'pasienPindahan')].humanReadableValues[0]
      jsonPath: $[0]
    - name: public_health_center
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'puskesmas')].values[0]
      jsonPath: $[0]
    - name: is_poor_family
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'gakinTidak')].humanReadableValues[0]
      jsonPath: $[0]
    - name: profession
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'pekerjaan')].humanReadableValues[0]
      jsonPath: $[0]
    - name: village
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'Village')].values[0]
      jsonPath: $[0]
    - name: province
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'Province')].values[0]
      jsonPath: $[0]
    - name: district
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'District')].values[0]
      jsonPath: $[0]
    - name: age
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'umur')].values[0]
      jsonPath: $[0]
    - name: transfer_date
      typeName: date
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'tglPindah')].values[0]
      jsonPath: $[0]
    - name: religion
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'agama')].humanReadableValues[0]
      jsonPath: $[0]
