destination-database:
  schemaName: sid_anc
  tables:

  - name: ${destination-database.schemaName}.client
    columns:
    - name: source_id
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_date_deleted
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_server_version
      typeName: integer
      sourceColumnName: server_version
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: rev
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._rev
    - name: type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.type
    - name: gender
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.gender
    - name: first_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: last_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.lastName
    - name: home_address
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].addressFields.address2
    - name: age
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.age
    - name: estimated_delivery_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.edd
    - name: red_flag_count
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.red_flag_count
    - name: yellow_flag_count
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.yellow_flag_count
    - name: contact_status
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.contact_status
    - name: previous_contact_status
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.previous_contact_status
    - name: next_contact
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.next_contact
    - name: next_contact_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.next_contact_date
    - name: last_contact_record_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.last_contact_record_date
    - name: visit_start_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.visit_start_date
    - name: date_removed
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.date_removed
    - name: birth_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.birthdate
    - name: birthdate_approx
      typeName: date
      sourceColumnName: json
      jsonPath: $.birthdateApprox
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: date_edited
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateEdited
    - name: anc_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.identifiers.ANC_ID
    - name: server_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: client_database_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.clientDatabaseVersion
    - name: client_application_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.clientApplicationVersion