destination-database:
  schemaName: sid3
  tables:
  - name: ${destination-database.schemaName}.client_ibu
    columns:
    - name: source_${destination-database.tables[0].columns[0].sourceColumnName}
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_${destination-database.tables[0].columns[1].sourceColumnName}
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: document_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: full_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: husband_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.lastName
    - name: province
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].stateProvince
    - name: district
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].countyDistrict
    - name: village
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].cityVillage
    - name: address
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0].addressFields.address3
    - name: birth_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.birthdate
    - name: nik
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.nik
    - name: mother_registration_number
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.NoIbu
    - name: anc_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.anc_id
    - name: traditional_birth_attendant
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.NamaDukun
    - name: community_health_worker_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.attributes.NamaKader
    - name: server_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
  - name: ${destination-database.schemaName}.client_anak
    columns:
    - name: source_${destination-database.tables[1].columns[0].sourceColumnName}
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_${destination-database.tables[1].columns[1].sourceColumnName}
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: document_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._id
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: base_entity_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: full_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: birth_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.birthdate
    - name: server_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: mother_base_entity_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.relationships.ibuCaseId[0]
    - name: openmrs_uuid
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.relationships.ibuCaseId[0]
    - name: gender
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.gender
    - name: date_edited
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateEdited
  - name: ${destination-database.schemaName}.identitas_ibu
    columns:
    - name: event_id
      typeName: varchar
      sourceColumnName: id
      isUnique: true
    - name: document_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._id
    - name: mother_base_entity_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: location_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.locationId
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: event_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.eventDate
    - name: client_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.version
    - name: server_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: provider_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.providerId
    - name: registration_date
      typeName: date
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'registrationDate')].values[0]
      jsonPath: $[0]
    - name: mobile_phone_number
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'NomorTelponHp')].values[0]
      jsonPath: $[0]
