destination-database:
  schemaName: sid_rdt
  tables:

  - name: ${destination-database.schemaName}.client
    columns:
    - name: source_id
      typeName: bigserial
      sourceColumnName: id
      isUnique: true
    - name: source_date_deleted
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_server_version
      typeName: integer
      sourceColumnName: server_version
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: rev
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._rev
    - name: type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.type
    - name: gender
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.gender
    - name: team_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.teamId
    - name: first_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.firstName
    - name: last_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.lastName
    - name: address1
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.addresses[0]
    - name: birth_date
      typeName: date
      sourceColumnName: json
      jsonPath: $.attributes.birthdate
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: location_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.locationId
    - name: date_edited
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateEdited
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: server_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion

  - name: ${destination-database.schemaName}.covid_patient_registration
    columns:
    - name: event_id
      typeName: varchar
      sourceColumnName: id
      isUnique: true
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: source_date_deleted
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_server_version
      typeName: integer
      sourceColumnName: server_version
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: rev
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._rev
    - name: team
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.team
    - name: type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.type
    - name: team_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.teamId
    - name: details_form_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.details.formVersion
    - name: details_app_version_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.details.appVersionName
    - name: client_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.version
    - name: server_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: duration
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.duration
    - name: event_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.eventDate
    - name: entity_type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.entityType
    - name: location_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.locationId
    - name: provider_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.providerId
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: form_submission_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.formSubmissionId
    - name: national_id_type
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'national_id_type')].values[0]
      jsonPath: $[0]
    - name: government_id_no
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'government_id_no')].values[0]
      jsonPath: $[0]
    - name: age
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'age')].values[0]
      jsonPath: $[0]
    - name: patient_phone_number
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'patient_phone_number')].values[0]
      jsonPath: $[0]
    - name: patient_email_address
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'patient_email_address')].values[0]
      jsonPath: $[0]
    - name: gvt_id_street_address
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'gvt_id_street_address')].values[0]
      jsonPath: $[0]
    - name: gvt_id_province
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'gvt_id_province')].values[0]
      jsonPath: $[0]
    - name: gvt_id_city
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'gvt_id_city')].values[0]
      jsonPath: $[0]
    - name: domicile_same_as_gvt_id_address
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'domicile_same_as_gvt_id_address')].values[0]
      jsonPath: $[0]
    - name: patient_whatsapp
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'patient_whatsapp')].values[0]
      jsonPath: $[0]
    - name: head_of_household_no
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'head_of_household_no')].values[0]
      jsonPath: $[0]
    - name: taken_tests_before
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'taken_tests_before')].values[0]
      jsonPath: $[0]
    - name: start_date_time
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'start')].values[0]
      jsonPath: $[0]
    - name: end_date_time
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'end')].values[0]
      jsonPath: $[0]
    - name: deviceid
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'deviceid')].values[0]
      jsonPath: $[0]
    - name: subscriberid
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'subscriberid')].values[0]
      jsonPath: $[0]
    - name: simserial
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'simserial')].values[0]
      jsonPath: $[0]
    - name: phone_manufacturer
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_manufacturer')].values[0]
      jsonPath: $[0]
    - name: app_version
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'app_version')].values[0]
      jsonPath: $[0]
    - name: phone_os_version
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_os_version')].values[0]
      jsonPath: $[0]
    - name: phone_model
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_model')].values[0]
      jsonPath: $[0]
    - name: last_known_location
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'last_known_location')].values[0]
      jsonPath: $[0]

  - name: ${destination-database.schemaName}.covid_wbc
    columns:
    - name: event_id
      typeName: varchar
      sourceColumnName: id
      isUnique: true
    - name: base_entity_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.baseEntityId
    - name: source_date_deleted
      typeName: timestamp
      sourceColumnName: date_deleted
    - name: source_server_version
      typeName: integer
      sourceColumnName: server_version
    - name: document_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $._id
    - name: rev
      typeName: varchar
      sourceColumnName: json
      jsonPath: $._rev
    - name: team
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.team
    - name: type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.type
    - name: team_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.teamId
    - name: details_form_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.details.formVersion
    - name: details_app_version_name
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.details.appVersionName
    - name: client_version_epoch
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.version
    - name: server_version
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.serverVersion
    - name: duration
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.duration
    - name: event_date
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.eventDate
    - name: entity_type
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.entityType
    - name: location_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.locationId
    - name: provider_id
      typeName: varchar
      sourceColumnName: json
      jsonPath: $.providerId
    - name: date_created
      typeName: timestamp with time zone
      sourceColumnName: json
      jsonPath: $.dateCreated
    - name: form_submission_id
      typeName: varchar
      typeLength: 36
      sourceColumnName: json
      jsonPath: $.formSubmissionId
    - name: leukocyte
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'leukocyte')].values[0]
      jsonPath: $[0]
    - name: lymphocytes
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'lymphocytes')].values[0]
      jsonPath: $[0]
    - name: platelets
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'platelets')].values[0]
      jsonPath: $[0]
    - name: date_wbc_conducted
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'date_wbc_conducted')].values[0]
      jsonPath: $[0]
    - name: start_date_time
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'start')].values[0]
      jsonPath: $[0]
    - name: end_date_time
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'end')].values[0]
      jsonPath: $[0]
    - name: deviceid
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'deviceid')].values[0]
      jsonPath: $[0]
    - name: subscriberid
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'subscriberid')].values[0]
      jsonPath: $[0]
    - name: simserial
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'simserial')].values[0]
      jsonPath: $[0]
    - name: phone_manufacturer
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_manufacturer')].values[0]
      jsonPath: $[0]
    - name: app_version
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'app_version')].values[0]
      jsonPath: $[0]
    - name: phone_os_version
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_os_version')].values[0]
      jsonPath: $[0]
    - name: phone_model
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'phone_model')].values[0]
      jsonPath: $[0]
    - name: last_known_location
      typeName: varchar
      sourceColumnName: json
      jsonFilter: $.obs[?(@.formSubmissionField == 'last_known_location')].values[0]
      jsonPath: $[0]
