source-database:
  tables:
  - destinationTableName: ${destination-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[1].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[1].name}
      WHERE ${source-database.tables[1].idColumnName} > %s
      AND "json" ->> 'eventType' = 'covid_patient_registration'
      ORDER BY ${source-database.tables[1].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[2].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[2].name}
      WHERE ${source-database.tables[2].idColumnName} > %s
      AND "json" ->> 'eventType' = 'covid_wbc'
      ORDER BY ${source-database.tables[2].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[3].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[3].name}
      WHERE ${source-database.tables[3].idColumnName} > %s
      AND "json" ->> 'eventType' = 'sample_delivery_details'
      ORDER BY ${source-database.tables[3].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[4].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[4].name}
      WHERE ${source-database.tables[4].idColumnName} > %s
      AND "json" ->> 'eventType' = 'covid_rdt_test'
      ORDER BY ${source-database.tables[4].idColumnName} ASC
    idColumnName: id
    lastId: 0

#covid_xray
#patient_diagnostics
#sample_collection