source-database:
  tables:
  - destinationTableName: ${destination-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[1].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[1].name}
      WHERE ${source-database.tables[1].idColumnName} > %s
      AND "json" ->> 'eventType' = 'covid_patient_registration'
      ORDER BY ${source-database.tables[1].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[2].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[2].name}
      WHERE ${source-database.tables[2].idColumnName} > %s
      AND "json" ->> 'eventType' = 'covid_wbc'
      ORDER BY ${source-database.tables[2].idColumnName} ASC
    idColumnName: id
    lastId: 0

#covid_patient_registration
#covid_wbc
#sample_delivery_details
#covid_rdt_test
#covid_xray
#patient_diagnostics
#sample_collection