source-database:
  tables:
  - destinationTableName: ${destination-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      AND "json" ->> 'firstName' != '-'
      AND "json" ->> 'lastName' != '-'
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[1].name}
    name: core.client
    query: SELECT c.*, (
        SELECT
          event_json.obs_data -> 'values' ->> 0 AS child_full_name
        FROM (
          SELECT
            jsonb_array_elements(
              (
                SELECT e."json"
                FROM core."event" e
                WHERE e."json" ->> 'baseEntityId' = c."json" ->> 'baseEntityId'
                AND e."json" ->> 'eventType' = 'Child Registration'
                ORDER BY e."json" ->> 'dateCreated' DESC
                LIMIT 1
              ) -> 'obs'
            ) AS obs_data
          ) event_json
        WHERE
          event_json.obs_data ->> 'formSubmissionField' = 'namaBayi'
        LIMIT 1
      )
      FROM ${source-database.tables[1].name} c
      WHERE c.${source-database.tables[1].idColumnName} > %s
      AND c."json" ->> 'firstName' = '-'
      AND c."json" ->> 'lastName' = '-'
      ORDER BY ${source-database.tables[1].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[2].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[2].name}
      WHERE ${source-database.tables[2].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Identitas Ibu'
      ORDER BY ${source-database.tables[2].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[3].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[3].name}
      WHERE ${source-database.tables[3].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Tambah ANC'
      ORDER BY ${source-database.tables[3].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[4].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[4].name}
      WHERE ${source-database.tables[4].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kunjungan ANC'
      ORDER BY ${source-database.tables[4].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[5].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[5].name}
      WHERE ${source-database.tables[5].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kunjungan ANC Lab Test'
      ORDER BY ${source-database.tables[5].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[6].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[6].name}
      WHERE ${source-database.tables[6].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kunjungan ANC integrasi'
      ORDER BY ${source-database.tables[6].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[7].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[7].name}
      WHERE ${source-database.tables[7].idColumnName} > %s
      AND "json" ->> 'eventType' = 'rencana persalinan'
      ORDER BY ${source-database.tables[7].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[8].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[8].name}
      WHERE ${source-database.tables[8].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Dokumentasi Persalinan'
      ORDER BY ${source-database.tables[8].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[9].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[9].name}
      WHERE ${source-database.tables[9].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kunjungan PNC'
      ORDER BY ${source-database.tables[9].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[10].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[10].name}
      WHERE ${source-database.tables[10].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Child Registration'
      ORDER BY ${source-database.tables[10].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[11].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[11].name}
      WHERE ${source-database.tables[11].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kunjungan neonatal'
      ORDER BY ${source-database.tables[11].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[12].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[12].name}
      WHERE ${source-database.tables[12].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kohort Kunjungan Bayi Perbulan'
      ORDER BY ${source-database.tables[12].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[13].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[13].name}
      WHERE ${source-database.tables[13].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Imunisasi Bayi'
      ORDER BY ${source-database.tables[13].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[14].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[14].name}
      WHERE ${source-database.tables[14].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kunjungan Balita'
      ORDER BY ${source-database.tables[14].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[15].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[15].name}
      WHERE ${source-database.tables[15].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Tambah Bayi'
      ORDER BY ${source-database.tables[15].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[16].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[16].name}
      WHERE ${source-database.tables[16].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Tambah KB'
      ORDER BY ${source-database.tables[16].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[17].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[17].name}
      WHERE ${source-database.tables[17].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Kohort Pelayanan KB'
      ORDER BY ${source-database.tables[17].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[18].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[18].name}
      WHERE ${source-database.tables[18].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Post-partum KB'
      ORDER BY ${source-database.tables[18].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[19].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[19].name}
      WHERE ${source-database.tables[19].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Penutupan Ibu'
      ORDER BY ${source-database.tables[19].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[20].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[20].name}
      WHERE ${source-database.tables[20].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Penutupan ANC'
      ORDER BY ${source-database.tables[20].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[21].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[21].name}
      WHERE ${source-database.tables[21].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Penutupan PNC'
      ORDER BY ${source-database.tables[21].idColumnName} ASC
    idColumnName: id
    lastId: 0
