source-database:
  tables:
  - destinationTableName: ${destination-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0
