source-database:
  tables:
  - destinationTableName: ${destination-database.tables[0].name}
    name: core.client
    query: SELECT * FROM ${source-database.tables[0].name}
      WHERE ${source-database.tables[0].idColumnName} > %s
      ORDER BY ${source-database.tables[0].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[1].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[1].name}
      WHERE ${source-database.tables[1].idColumnName} > %s
      AND "json" ->> 'eventType' = 'ANC Registration'
      ORDER BY ${source-database.tables[1].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[2].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[2].name}
      WHERE ${source-database.tables[2].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Quick Check'
      ORDER BY ${source-database.tables[2].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[3].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[3].name}
      WHERE ${source-database.tables[3].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Profile'
      ORDER BY ${source-database.tables[3].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[4].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[4].name}
      WHERE ${source-database.tables[4].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Symptoms and Follow-up'
      ORDER BY ${source-database.tables[4].idColumnName} ASC
    idColumnName: id
    lastId: 0

  - destinationTableName: ${destination-database.tables[5].name}
    name: core.event
    query: SELECT * FROM ${source-database.tables[5].name}
      WHERE ${source-database.tables[5].idColumnName} > %s
      AND "json" ->> 'eventType' = 'Physical Exam'
      ORDER BY ${source-database.tables[5].idColumnName} ASC
    idColumnName: id
    lastId: 0
